/*
 * DIO.h
 *
 *  Created on: 10 Sep 2022
 *      Author: Hassan Ghandoor
 */

#ifndef DIO_H_
#define DIO_H_
// DECLARING PORTS
#define PORTA_NUM 0
#define PORTB_NUM 1
#define PORTC_NUM 2
#define PORTD_NUM 3
// DECLARING PINS
#define PIN0 0
#define PIN1 1
#define PIN2 2
#define PIN3 3
#define PIN4 4
#define PIN5 5
#define PIN6 6
#define PIN7 7
// DECLARING OUTPUTS AND INPUTS
#define INPUT 0
#define OUTPUT 1
// DECLARING FUNC. STATUS BASED ON USER'S INPUTS
#define OK 0
#define NOK 1
// DECLARING OUTPUT PINS'STATUS
#define LOW 0
#define HIGH 1
//DECLARING WHOLE PORT'S PIN VALUES
#define ALL_HIGH 0xFF
// PULL UP RESISTOR ACTIVATION
#define ACTIVATE_PULLUP 1
// FUNCTIONS PROTOTYPES
u8 DIO_SET_PIN_DIRECTION (u8 PORT_NUM, u8 PIN_NUM, u8 PIN_DIRECTION);
u8 DIO_SET_PIN_VALUE (u8 PORT_NUM, u8 PIN_NUM, u8 PIN_VALUE);
u8 DIO_SET_PORT_DIRECTION (u8 PORT_NUM, u8 PORT_DIRECTION );
u8 DIO_SET_PORT_VALUE (u8 PORT_NUM, u8 PORT_VALUE );

#endif /* DIO_H_ */
